# Generated by Django 5.1.7 on 2025-04-07 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_completed_games', models.IntegerField(default=0)),
                ('completed_easy', models.IntegerField(default=0)),
                ('completed_medium', models.IntegerField(default=0)),
                ('completed_hard', models.IntegerField(default=0)),
                ('best_time_easy', models.FloatField(blank=True, null=True)),
                ('best_time_medium', models.FloatField(blank=True, null=True)),
                ('best_time_hard', models.FloatField(blank=True, null=True)),
                ('unlocked_memories', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
