# Generated by Django 5.1.7 on 2025-04-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='completed_easy_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='completed_hard_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='completed_medium_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='total_completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
