# Generated by Django 5.1.7 on 2025-03-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='block_items',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='game',
            name='block_rooms',
            field=models.JSONField(default=list),
        ),
    ]
