# Generated by Django 5.1.7 on 2025-03-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_game_block_items_game_block_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='group_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
