# Generated by Django 5.1.7 on 2025-03-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_item_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='prefilled',
            field=models.BooleanField(default=False),
        ),
    ]
